### PR TITLE
make metadata available from xradia microscopes

### PR DESCRIPTION
**Pull request by skylarjhdownes**
.xrm .txrm and .txm files all contain useful metadata.  This PR exposes some of that data in a way that will be easy to extend to include other metadata as desired.

### CODE REVIEW

**Comment by skylarjhdownes** [comment]
Related to #36.

**Comment by decarlof** [comment]
@skylarjhdownes do we need to keep the [test_data](https://github.com/skylarjhdownes/dxchange/tree/master/test/test_data) for tomopy test like gridrec, art etc. here too or is better to limit to file i/o test data only?

**Comment by dgursoy** [comment]
These data tests should be in tomopy side I guess.

**Comment by skylarjhdownes** [comment]
The only data files that are currently being used by dxchange tests are "test_chip00.xrm", "test_chip01.xrm", and "txrm_test_chip_tomo.txrm".  dxchange definitely should have it's own test suite.  I just pulled the test data over from TomoPy early on because I didn't know exactly which data I needed.  It's probable that not all of it needs to be included.

**Comment by decarlof** [comment]
I suggest to keep only the data format templates and remove the rest.

**Comment by skylarjhdownes** [comment]
Like so?

**Comment by decarlof** [comment]
perfect! thanks a lot for the great contribution. I will add example/update the docs to add 8-BM shortly on a separate pull request.

**Pull request merged**
