### PR TITLE
Working on adding support for aps_8bm beamline.

### PR DESCRIPTION
**Pull request by skylarjhdownes**
Code review welcome.  

tomopy.find_center() no longer has an emission argument, so I assume the reconstruction scripts that were sending it one were out of date?

I'm not sure that this beamline shouldn't just be referencing another one in the way read_aps_2bm() is.

### CODE REVIEW

**Comment by decarlof** [comment]
xrm/txrm are already supported by data exchange (see reader); the xrm reader is used by the aps 26 id reader (they have an xradia system there). Can you share a txrm data set from 8bm? Just to make sure it us tge same 26 has; i noticed xradia has different cersion fir the txrm format

**Comment by skylarjhdownes** [comment]
Maybe I'm missing something, but it seems to me that only the reading of xrm files/stacks is supported?  There was no read_txrm function before I wrote this one.  Is it named something else?

I've got an Xradia txrm of some Siemen's star images from 8bm that I can share, should give a reference for how the file is structured: 
[20160313_1231_star_f2.zip](https://github.com/data-exchange/dxchange/files/382014/20160313_1231_star_f2.zip)

**Comment by decarlof** [comment]
@skylarjhdownes you are correct. I had an [old version](https://github.com/data-exchange/dxchange/blob/72c30d0dcfbd32cf49e25e5119dd318004674cc7/xtomo/src/xtomo_reader.py) that I eventually dropped and not maintained anymore since I realized newer txrm data I was getting from 26-ID and some table top systems where not compatible. Since then I have been redirecting xradia user to txm wizard to convert to tiff. Did you also experience txrm file format back compatibility issue?  If these are not there anymore, I agree with you, it is time to add txrm support back to data exchange. This will also spark the development of new realignment preprocessing routine in tomopy (btw do you need to realign projections from 8-BM?). I will add the 8-BM Siemens star to my test dataset library, run a test reconstruction and accept your pull request. thanks a lot francesco

**Comment by skylarjhdownes** [comment]
I'm learning as I go, so I don't know about any back compatibility issues yet.  I'm working on reconstructing some data that others obtained from 8bm, some of which is in the txrm format.  It was all taken in the past year.  My understanding is that 8-BM requires some realignment, I've been seeing some regular jitter in our test data that comes from the rotation stage.

**Comment by decarlof** [comment]
_list_file_stack is not only used by read_xrm_stack => moving the trailing digit removal logic into it's own function will affect the call of all other stack readers. I think is better to reverse this change. All other changes on the 8-BM reader are good to go.

**Comment by skylarjhdownes** [comment]
As far as I know, _list_file_stack is only used for reading stacks of tiffs, hdf5s, and xrms.  The digit argument is redundant, since the number of digits is always available in the filename argument.  Are you talking about the digit argument when you say "index"?

My understanding is that there is pushback against changing the inputs to the read_xrm_stack, read_tiff_stack, and read_hdf5_stack functions, since that could break existing scripts.  Is that correct?

**Comment by decarlof** [comment]
@skylarjhdownes Yes I mean the digit argument and that is correct we have users calling directly the read_stack functions and the pull request as is now breaks the read stack for hdf5 and tiffs. Your approach is correct but we should probably go through a deprecation cycle to adopted it.

**Comment by skylarjhdownes** [comment]
I've added a deprecation warning for now.  The digit argument is still there so current scripts shouldn't break, it just doesn't do anything.

**Comment by decarlof** [comment]
@skylarjhdownes ok is passing the test on full size data set for all facilities.

**Comment by decarlof** [comment]
@skylarjhdownes all tests passed.

**Pull request merged**
