### PR TITLE
Removed h5py usage in read_als_832h5

### PR DESCRIPTION
**Pull request by lbluque**

### CODE REVIEW

**Comment by decarlof** [comment]
is the _find_dataset_group only used by ALS BL8.3.2 hdf5 file? The more general comment 
    
Finds the group name containing the stack of projections datasets within
hdf5 file with a stack of images

maybe misleading for other hdf5 format 'stacking' the images into a single array.
If this is the case I would suggest to replace the comment in _find_dataset_group with

    Finds the group name containing the stack of projections datasets within
    an ALS BL8.3.2 hdf5 file  containing a stack of images

**Comment by decarlof** [comment]
Would it be possible to share a template data set from the APS BL3.3.2 beamline so I can add it in the DXchange validation tests? If so please share your globus id and I will give you write permission at:

https://www.globus.org/app/transfer?origin_id=5e6eeff0-00c4-11e6-a71b-22000bf2d559&origin_path=%2F
thanks

**Comment by lbluque** [comment]
There is actually one in the test/data directory of tomopy. The file is
called read_stack.h5 this is a template for an ALS 8.3.2 dataset that can
be used for tests in dxchange.

Best,
Luis

**Comment by lbluque** [comment]
Let me know if you want an real dataset from the beamline to test.

**Comment by data-exchange** [comment]
Thank you Luis
I am actually trying to collect real size data sets from all facilities, I already have a tiff version from the als and i'd to get a full size hdf as generated by your converter
F


Sent by T-mobile

**Comment by lbluque** [comment]
No problem, I can send you a real dataset via globus. My globus id is:
lbluque.

**Comment by data-exchange** [comment]
Thanks a lot, just added you with write permission at the globus link below

Francesco 

Sent by T-mobile

**Pull request merged**
