### PR TITLE
report for aps_1id data and vtk writing support 

### PR DESCRIPTION
**Pull request by KedoKudo**
Add a function to generated report based on the metadata from aps_1id tomography experiment, and a function to export reconstruction results to VTK (vtr, rectangular grid).

### CODE REVIEW

**Comment by decarlof** [comment]
@KedoKudo may you give me a test data set so I can see how the report function works? This could be interesting to add to other beamline

**Comment by decarlof** [comment]
no too big for github. Please send me an email and I will give you an
upload link

**Comment by KedoKudo** [comment]
@decarlof I moved the report function to writer.py as suggested.  Please let me know if there is anything else that needs to be done before merging.

**Comment by decarlof** [comment]
@KedoKudo perfect, thanks

**Pull request merged**
