### PR TITLE
Update mctDetectorAttributes.xml

### PR DESCRIPTION
**Pull request by cshoyuelos**
Updated version for PG1 camera in 2BM and info of monochromatic beam setup in local tomography mode

### CODE REVIEW

**Comment by decarlof** [comment]
Has this been tested with the Point grey? Formatting of the xml is off (extra indents in table and mirror) entries. Also the xml describing the layout of the hdf5 file is missing. Several useful metadata definition are missing. Please use the txm xmls as template. 
Documentation for the data exchange is in the xtomo/docs folder of this repo as pdf.
I am finalizing a new web based version of the docs that I will merge in a few days. This is at 
http://dxfile.readthedocs.org/  if you want to have a preview or use this version of the docs is uptodate for the xml part (under Example/areadetector)

**Comment by data-exchange** [comment]
@cshoyuelos Carmen the cshoyuelos branch is behind master by 30+ commits. Please do a git pull before continuing on this pull request

**Comment by decarlof** [comment]
@cshoyuelos Carmen there are merging conflicts. Please do a git pull then replace the mct and mctDetectorAttibute xml files and continue the pull request.

motors: you are saving .VAL, these can be reset by user at any time (changing offset), better to also save DVAL.
Slits: hslits_us_gap etc. are derived quantities. I suggest to save motor position instead. Create instrument/slits and add  motor under instrument/slits/setup; add slits to the docs.
sample: motor positions should go under instrument/sample/setup; theta under sample will only save the last position of the rotary stage; it should be removed from here since theta is already saved at each frame.
flag: create an instrument/flag and add motor position under setup; update the docs.
savedest: is not defined in http://dxfile.readthedocs.org/en/latest/source/xraytomo.html: I think this is the Sample folder, if so please add a laber "folder" instrument/sample/folder and update the docs.
FileName  is not defined in the mctAttribute.

please refer to http://dxfile.readthedocs.org/en/latest/source/xraytomo.html for label name definition; if someone is missing feel free to add it in your xml file and update the docs.

**Comment by decarlof** [comment]
@cshoyuelos got it. I am closing this since the project moved to dxfile. I can see a new pull request there

**Pull request closed without merging**
